version: "3.3"
services:
  jsbuild:
    build:
      context: .
      dockerfile: Dockerfile.npm
    restart: 'no'
    volumes:
      - '.:/code'
  web:
    build: .
    ports:
      - "8087:80"
    volumes:
      - /var/www/html/bin/usr
      - .:/var/www/html/
    links:
      - memcached
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
  cron:
    build: .
    entrypoint: "php console cron media"
    restart: unless-stopped
    volumes:
      - /var/www/html/bin/usr
      - .:/var/www/html/
    links:
      - memcached
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
  memcached:
    image: memcached:latest
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: www
      MYSQL_PASSWORD: test
    ports:
      - "3387:3306"
