<?php namespace spitfire\validation\rules;


abstract class BaseRule implements \spitfire\validation\ValidationRule
{
	
	/**
	 * A message the validation error generated by this object should carry to give
	 * the end user information about the reason his input was rejected.
	 * 
	 * @var string
	 */
	private $message;
	
	/**
	 * Additional information given to the user in case the validation did not 
	 * succeed. This message can hold additional infos on how to solve the error.
	 * 
	 * @var string
	 */
	private $extendedMessage;
	
	/**
	 * 
	 * @todo Document
	 * @param string $message
	 * @param string $extendedMessage
	 */
	public function __construct($message, $extendedMessage = '') {
		$this->message = $message;
		$this->extendedMessage = $extendedMessage;
	}
	
	public function getMessage() {
		return $this->message;
	}

	public function getExtendedMessage() {
		return $this->extendedMessage;
	}	
	
	/**
	 * Tests a value with this validation rule. Returns the errors detected for
	 * this element or boolean false on no errors.
	 * 
	 * @param mixed $value
	 * @return \spitfire\validation\ValidationError|boolean
	 */
	abstract public function test($value);

}